package:
  name: mobile_clusters
  version: 0.1.2

source:
  path: .

build:
  noarch: python
  script: "python -m pip install -e ."

requirements:
  host:
    - python >=3.10
    - pip
    - build
    - setuptools
    - setuptools-scm
  run:
    - python >=3.10
    - pandas >=2.0.0
    - biopython >=1.84
    - tqdm >=2.0.0
    - matplotlib >=3.0.0
    - diamond >=2.0.0
    - mmseqs2 >=15.6
    - mcl >=22-282


about:
  homepage: https://github.com/Ellouzlab/make_mcl_clusters
  license: MIT
  summary: "A package to create MCL clusters"
  description: |
    A package to create MCL clusters.
  repository: https://github.com/Ellouzlab/make_mcl_clusters

extra:
  recipe-maintainers:
    - sulmanm1
